
import java.awt.Color;
import java.awt.Component;
import java.awt.ComponentOrientation;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author useR
 */
public class StudentData extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form StudentData
     */
    public StudentData() {
        initComponents();

        Object[] col = {"StudentID", "Course", "TotalScore", "Average", "Ranking", "Maths", "English", "Biology", "Computing", "Chemistry", "Physics", "AddMaths", "Business"};
        model.setColumnIdentifiers(col);
        jTable1.setModel(model);
        conn = StudentData.connectDB();
        updateTable();
    }

    public static Connection connectDB() {
        try {
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection("jdbc:sqlite:C:\\Users\\useR\\Documents\\NetBeansProjects\\Student Management Systems\\src\\lib\\Student.db");
            return conn;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        studentID = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        comboCourse = new javax.swing.JComboBox<>();
        ranking = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        average = new javax.swing.JTextField();
        totalScore = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        maths = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        english = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        biology = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        computing = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        business = new javax.swing.JTextField();
        addMaths = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        physics = new javax.swing.JTextField();
        chemistry = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextTranscript = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        transcriptBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204), 12), "Student Record", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255), 12), "Student Record", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel3.setToolTipText("");
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Course:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        lastName.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastNameKeyTyped(evt);
            }
        });
        jPanel3.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 150, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Student ID:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Name:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        studentID.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        studentID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studentIDKeyTyped(evt);
            }
        });
        jPanel3.add(studentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 150, -1));

        name.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });
        jPanel3.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 150, -1));

        comboCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course1", "Course2", "Course3", "Course4" }));
        jPanel3.add(comboCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 150, 30));

        ranking.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        ranking.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rankingKeyTyped(evt);
            }
        });
        jPanel3.add(ranking, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("Ranking");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("Average:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        average.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        average.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                averageKeyTyped(evt);
            }
        });
        jPanel3.add(average, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 150, -1));

        totalScore.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        totalScore.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalScoreKeyTyped(evt);
            }
        });
        jPanel3.add(totalScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 150, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setText("Total Score:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Last Name:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setText("Maths:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        maths.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        maths.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mathsKeyTyped(evt);
            }
        });
        jPanel3.add(maths, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setText("English:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));

        english.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        english.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                englishKeyTyped(evt);
            }
        });
        jPanel3.add(english, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 150, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setText("Biology:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        biology.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        biology.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                biologyKeyTyped(evt);
            }
        });
        jPanel3.add(biology, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 150, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setText("Computing:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, -1));

        computing.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        computing.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                computingKeyTyped(evt);
            }
        });
        jPanel3.add(computing, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 150, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel12.setText("Business:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        business.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        business.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                businessKeyTyped(evt);
            }
        });
        jPanel3.add(business, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 150, -1));

        addMaths.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        addMaths.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addMathsKeyTyped(evt);
            }
        });
        jPanel3.add(addMaths, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 150, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setText("Add Maths:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel14.setText("Physics:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        physics.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        physics.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                physicsKeyTyped(evt);
            }
        });
        jPanel3.add(physics, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 150, -1));

        chemistry.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        chemistry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                chemistryKeyTyped(evt);
            }
        });
        jPanel3.add(chemistry, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 150, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel15.setText("Chemistry:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 380));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255), 12), "Transcript", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextTranscript.setColumns(20);
        jTextTranscript.setRows(5);
        jScrollPane2.setViewportView(jTextTranscript);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 430, 320));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 470, 380));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Course Code", "Maths", "English", "Biology", "Computing", "Chemistry", "Physics", "Add Maths", "Business", "Total Score", "Average", "Ranking"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 1400, 340));

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setText("Add / Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        transcriptBtn.setBackground(new java.awt.Color(153, 255, 255));
        transcriptBtn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        transcriptBtn.setText("Transcript");
        transcriptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transcriptBtnActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonReset.setBackground(new java.awt.Color(153, 255, 255));
        jButtonReset.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(50, 50, 50)
                .addComponent(transcriptBtn)
                .addGap(34, 34, 34)
                .addComponent(jButton3)
                .addGap(65, 65, 65)
                .addComponent(jButtonReset)
                .addGap(69, 69, 69)
                .addComponent(jButton2)
                .addGap(107, 107, 107)
                .addComponent(jButton5)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(transcriptBtn)
                    .addComponent(jButton3)
                    .addComponent(jButtonReset)
                    .addComponent(jButton5)
                    .addComponent(jButton2))
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 1400, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.getContentPane().setBackground(Color.blue);
    }//GEN-LAST:event_formWindowActivated

    private void mathsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mathsKeyTyped
        setDigits(evt);
    }//GEN-LAST:event_mathsKeyTyped

    private void englishKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_englishKeyTyped
        setDigits(evt);
    }//GEN-LAST:event_englishKeyTyped

    private void biologyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_biologyKeyTyped
        setDigits(evt);
    }//GEN-LAST:event_biologyKeyTyped

    private void computingKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_computingKeyTyped
        setDigits(evt);
    }//GEN-LAST:event_computingKeyTyped

    private void chemistryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chemistryKeyTyped
        setDigits(evt);
    }//GEN-LAST:event_chemistryKeyTyped

    private void physicsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_physicsKeyTyped
        setDigits(evt);
    }//GEN-LAST:event_physicsKeyTyped

    private void addMathsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addMathsKeyTyped
        setDigits(evt);
    }//GEN-LAST:event_addMathsKeyTyped

    private void businessKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_businessKeyTyped
        setDigits(evt);
    }//GEN-LAST:event_businessKeyTyped

    private void studentIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentIDKeyTyped
        setDigits(evt);
    }//GEN-LAST:event_studentIDKeyTyped

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped

    }//GEN-LAST:event_nameKeyTyped

    private void lastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameKeyTyped

    }//GEN-LAST:event_lastNameKeyTyped

    private void totalScoreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalScoreKeyTyped
        setDigits(evt);
    }//GEN-LAST:event_totalScoreKeyTyped

    private void averageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_averageKeyTyped
        setDigits(evt);
    }//GEN-LAST:event_averageKeyTyped

    private void rankingKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rankingKeyTyped
        setDigits(evt);
    }//GEN-LAST:event_rankingKeyTyped

    private JFrame frame;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to EXIT", "Student Result System",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed

        lastName.setText(null);
        studentID.setText(null);
        name.setText(null);
        totalScore.setText(null);
        average.setText(null);
        ranking.setText(null);
        maths.setText(null);
        english.setText(null);
        biology.setText(null);
        computing.setText(null);
        chemistry.setText(null);
        physics.setText(null);
        addMaths.setText(null);
        business.setText(null);
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double[] r = new double[14];
        r[0] = Double.parseDouble(maths.getText());
        r[1] = Double.parseDouble(english.getText());
        r[2] = Double.parseDouble(biology.getText());
        r[3] = Double.parseDouble(computing.getText());
        r[4] = Double.parseDouble(chemistry.getText());
        r[5] = Double.parseDouble(physics.getText());
        r[6] = Double.parseDouble(addMaths.getText());
        r[7] = Double.parseDouble(business.getText());

        r[8] = (r[0] + r[1] + r[2] + r[3] + r[4] + r[5] + r[6] + r[7] / 8);
        r[9] = (r[0] + r[1] + r[2] + r[3] + r[4] + r[5] + r[6] + r[7]);

        String averageString = String.format("%.0f", r[8]);
        average.setText(averageString);

        String totalString = String.format("%.0f", r[9]);
        totalScore.setText(totalString);

        if (r[9] >= 700) {
            ranking.setText("1st");
        } else if (r[9] >= 600) {
            ranking.setText("2i");
        } else if (r[9] >= 500) {
            ranking.setText("2ii");
        } else if (r[9] >= 400) {
            ranking.setText("3rd");
        } else if (r[9] >= 300) {
            ranking.setText("CoHE");
        } else if (r[9] >= 200) {
            ranking.setText("Fail");
        }

        String sql = "INSERT INTO Student (StudentID, Name, LastName, Course, TotalScore, Average, Ranking, Maths, English, Biology, Computing, Chemistry, Physics, AddMaths, Business)"
                + "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, studentID.getText());
            pst.setString(2, name.getText());
            pst.setString(3, lastName.getText());
            pst.setString(4, comboCourse.getSelectedItem().toString());
            pst.setString(5, totalScore.getText());
            pst.setString(6, average.getText());
            pst.setInt(7, Integer.parseInt(ranking.getText()));
            pst.setString(8, maths.getText());
            pst.setString(9, english.getText());
            pst.setString(10, biology.getText());
            pst.setString(11, computing.getText());
            pst.setString(12, chemistry.getText());
            pst.setString(13, physics.getText());
            pst.setString(14, addMaths.getText());
            pst.setString(15, business.getText());

            pst.execute();
            JOptionPane.showMessageDialog(null, "System Update Completed");

            rs.close();
            pst.close();

            //updateTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void transcriptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transcriptBtnActionPerformed
        jTextTranscript.append("Student Result Recording System \n"
                + "==================================\n"
                + "StudentID: " + studentID.getText()
                + "Maths:\t\t\t" + maths.getText()
                + "\nEnglish:\t\t" + english.getText()
                + "\nBiology:\t\t" + biology.getText()
                + "\nComputing:\t\t" + computing.getText()
                + "\nChemistry:\t\t" + chemistry.getText()
                + "\nPhysics:\t\t" + physics.getText()
                + "\nAdd Maths:\t\t" + addMaths.getText()
                + "\nBusiness:\t\t" + business.getText()
                + "\n================================="
                + "\nTotal Score:\t\t" + totalScore.getText()
                + "\nAverage:\t\t" + average.getText()
                + "\nRanking:\t\t" + ranking.getText() + "\n"
        );
    }//GEN-LAST:event_transcriptBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MessageFormat header = new MessageFormat("Printing in Progress...");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        try {
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (Exception e) {
            System.err.format("No printer found", e.getMessage());
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      String sql ="delete from Student where StudentID=? ";
            try{
                pst=conn.prepareStatement(sql);
                pst.setString(1, studentID.getText());
                pst.execute();

                JOptionPane.showMessageDialog(null,"Record Deleted");

            }catch(Exception e){

                JOptionPane.showMessageDialog(null, e);
            }finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(Exception e){

                }
            }
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
      if(jTable1.getSelectedRow() == -1){
          if(jTable1.getRowCount() == 0)
              JOptionPane.showMessageDialog(null, "No data to delete");
           else
              JOptionPane.showMessageDialog(null, "Select a row to delete", "Student Result System", JOptionPane.OK_OPTION);
      } else {
          model.removeRow(jTable1.getSelectedRow());
      }
          
     
    }//GEN-LAST:event_jButton3ActionPerformed

    private void setDigits(java.awt.event.KeyEvent evt) {
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }

    /**
     * @param args the command line arguments
     */
    private void updateTable() {
        conn = StudentData.connectDB();
        if (conn != null) {
            String sql = "SELECT StudentID,Course,TotalScore,Average,Ranking,Maths,English,Biology,Computing,Chemistry,Physics,AddMaths,Business FROM Student";
            try {
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                Object[] columnData = new Object[13];

                while (rs.next()) {
                    columnData[0] = rs.getString("StudentID");
                    columnData[1] = rs.getString("Course");
                    columnData[2] = rs.getString("TotalScore");
                    columnData[3] = rs.getString("Average");
                    columnData[4] = Integer.parseInt(rs.getString("Ranking"));
                    columnData[5] = rs.getString("Maths");
                    columnData[6] = rs.getString("English");
                    columnData[7] = rs.getString("Biology");
                    columnData[8] = rs.getString("Computing");
                    columnData[9] = rs.getString("Chemistry");
                    columnData[10] = rs.getString("Physics");
                    columnData[11] = rs.getString("AddMaths");
                    columnData[12] = rs.getString("Business");

                    model.addRow(columnData);

                }
            } catch (NumberFormatException | SQLException e) {
            }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StudentData().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addMaths;
    private javax.swing.JTextField average;
    private javax.swing.JTextField biology;
    private javax.swing.JTextField business;
    private javax.swing.JTextField chemistry;
    private javax.swing.JComboBox<String> comboCourse;
    private javax.swing.JTextField computing;
    private javax.swing.JTextField english;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextTranscript;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField maths;
    private javax.swing.JTextField name;
    private javax.swing.JTextField physics;
    private javax.swing.JTextField ranking;
    private javax.swing.JTextField studentID;
    private javax.swing.JTextField totalScore;
    private javax.swing.JButton transcriptBtn;
    // End of variables declaration//GEN-END:variables
}
